### PR TITLE
Updated installation instructions

### PR DESCRIPTION
**Pull request by brylie**

### CODE REVIEW

**Comment by dcsan** [comment]
thanks! i guess i should pass this on upstream to @artwells

**Comment by artwells** [comment]
Thanks!  I just updated them yesterday, but the notice is always appreciated.

I've also  incorporating the other changes this fork has made, and added a little more functionality.

**Comment by dcsan** [comment]
i'm not sure how PRs to a fork work, if they automatically get propagated upstream, or just stop with the owner of the fork?

**Comment by artwells** [comment]
They stop with the fork owner, afaik.

**Pull request merged**
